---

- name: Install pre-reqs
  ansible.builtin.apt:
    pkg:
      - unzip
    state: present
    update_cache: true

- name: Create Pocketbase directory
  ansible.builtin.file:
    path: /opt/pocketbase
    state: directory
    owner: azureuser
    group: azureuser
    mode: 0755

- name: Download Pocketbase
  ansible.builtin.get_url:
    url: https://github.com/pocketbase/pocketbase/releases/download/v0.10.4/pocketbase_0.10.4_linux_amd64.zip
    dest: /tmp/pocketbase.zip
    mode: 0755

- name: Unzip Pocketbase
  ansible.builtin.unarchive:
    src: /tmp/pocketbase.zip
    dest: /opt/pocketbase/
    remote_src: true
